{
    "name": "FacturAPI - Colombia Electronic Invoice Base",
    "version": "0.1.0",
    "category": "Accounting/Localizations/EDI",
    "license": "LGPL-3",
    "summary": "Base module for FacturAPI integration with DIAN",
    "depends": [
        "account",
        "base_address_extended",
        "certificate",
        "uom",
        "base_vat",
        "l10n_co_verification_digit",
        "l10n_co_economic_activities",
        "l10n_co_withholding",
    ],
    "excludes": [
        "l10n_co_electronic_invoice",
        "l10n_co_electronic_invoice_self"
    ],
    "data": [
        "security/ir.model.access.csv",
        "data/ir_cron_data.xml",
        "data/res_country_state_data.xml",
        "data/res.city.csv",
        "data/uom_uom_data.xml",
        "data/account_tax_group_data.xml",
        "views/res_city_views.xml",
        "views/res_partner_views.xml",
        "views/res_config_settings_views.xml",
        "views/edi_format_views.xml",
        "views/account_journal_views.xml",
        "views/account_payment_term_views.xml",
        "views/account_tax_views.xml",
        "views/account_move_views.xml",
    ],
    "post_init_hook": "post_init_hook",
    "installable": True,
    "auto_install": False,
    "application": True,
}
